### ISSUE TITLE
filterdiff breaks diff headers output by git diff

### ISSUE THREAD

**Issue by iazz** [twaugh/patchutils#12]
When processing patches produced by git diff, filterdiff processes the first header line containing "diff --git a/foo b/foo" through output_header_line, which does strange things when filterdiff is called with --strip.
I doubt it's a good idea to pass all of the header lines through output_header_line with no regard to the actual kind of header line it is.

**Comment by twaugh** [comment]
Can you please give an example input, command line and output, along with the output you would expect?

**Comment by iazz** [comment]
I just did a test with a test git repository, containing only the file `test.txt` and containing the word "foo".  Then, after changing the contents of the file to the word "bar", `git diff` gives the following output:
```diff
diff --git a/test.txt b/test.txt
index 257cc56..5716ca5 100644
--- a/test.txt
+++ b/test.txt
@@ -1 +1 @@
-foo
+bar
```
But piping that into `filterdiff --strip=1` gives:
```diff
difftest.txt b/test.txt
index 257cc56..5716ca5 100644
--- test.txt
+++ test.txt
@@ -1 +1 @@
-foo
+bar
```
with the first header line clearly wrong.  The expected output is:
```diff
diff --git test.txt test.txt
index 257cc56..5716ca5 100644
--- test.txt
+++ test.txt
@@ -1 +1 @@
-foo
+bar
```

**Comment by twaugh** [comment]
Thanks, I've added a commit that adds a test-case for this failure.
