### ISSUE TITLE
filterdiff: corrupts git patches with "copy from"

### ISSUE THREAD

**Issue by leahneukirchen** [twaugh/patchutils#14]
When I run filterdiff 0.3.4 (or filterdiff -v) on attached patch,
the --- line is removed as well as the crud lines (ok),
and the copy/index lines (would be ok as well),
which results in a patch corruption.

```
crud

diff --git pod/perldelta.pod pod/perl5221delta.pod
similarity index 99%
copy from pod/perldelta.pod
copy to pod/perl5221delta.pod
index 257124a..5d01a4b 100644
--- pod/perldelta.pod
+++ pod/perl5221delta.pod
@@ -2,7 +2,7 @@

 =head1 NAME

-perldelta - what is new for perl v5.22.1
+perl5221delta - what is new for perl v5.22.1

 =head1 DESCRIPTION

crud
```

**Comment by sergiomb2** [comment]
If you remove or change keyword diff , all works , at least in my preliminary tests . Good catch

**Comment by twaugh** [comment]
Current master outputs the `---` line but not the `copy to` or `index` lines.
