### ISSUE TITLE
filterdiff: --strip breaks diff-lines

### ISSUE THREAD

**Issue by chneukirchen** [twaugh/patchutils#15]
I noticed the following misbehavior on your highly useful
filterdiff 0.3.4 tool:

```
% git diff HEAD~ | head -1
diff --git a/COPYING b/COPYING

% git diff HEAD~ | filterdiff --strip 1 | head -1
diffCOPYING b/COPYING
```

The ---/+++ lines are rewritten fine, but the diff-lines
aren't... (same without --git btw.)

**Comment by twaugh** [comment]
This is fixed in current master, most likely from #12.
