### ISSUE TITLE
http://cyberelk.net/tim/patchutils/ is out-of-date

### ISSUE THREAD

**Issue by jwilk** [twaugh/patchutils#21]
http://cyberelk.net/tim/patchutils/ was last updated in 2004 and it says:
> Anonymous CVS is available at sources.redhat.com:
> 
>     cvs -d:pserver:anoncvs@sources.redhat.com:/cvs/patchutils co patchutils

Unsurprisingly, these instructions no longer work.

Could you make the page point to this repository instead?

**Comment by twaugh** [comment]
Updated. Actually that's an old URL which had inadvertently not been redirecting.

**Comment by mcepl** [comment]
So, putting my bug triager hat on my head again, why is this ticket not closed?

**Comment by twaugh** [comment]
I never closed it. Good catch.
