### ISSUE TITLE
grepdiff: allow to search only additions/deletions

### ISSUE THREAD

**Issue by KangOl** [twaugh/patchutils#3]
It would be useful that grep only match addition or deletions.

**Comment by twaugh** [comment]
Yes, good idea. Suggested new option: --only-changed
This would cause only matches within changed '+/-/!' lines to be counted.

Want to have a go at coding it?

**Comment by KangOl** [comment]
In fact, my suggestion was about only matching addition **OR** deletion.

My use case is to write a git pre-commit hook that check I do not let any "debugger" keyword in my js files. But removing one should be allowed.

By the way, I can take a look at the code and provide a patch.

**Comment by twaugh** [comment]
I see. Yes, that makes sense. Perhaps it could be --only-match=add|remove|change|all, default is 'all'.

Then --only-match=add would only match hunks that add the matching string, and likewise for --only-match=remove. Either would match for --only-match=change, and additionally --only-match=all matches context lines. Does that sound better?

**Comment by KangOl** [comment]
That's perfect
