### ISSUE TITLE
Move installation files to GitHub

### ISSUE THREAD

**Issue by kocsenc** [twaugh/patchutils#6]
So the GitHub repo does not contain the files for installation, mainly `compile`. The Installation instructions should also be clear within the README for GH uses and using compiling markdown.

**Comment by sergiomb2** [comment]
It does contains files for installation in INSTALL file in root , I don't understand the rest of the request,  GH means github ?

**Comment by kocsenc** [comment]
GH does mean GitHub. My apologies for being unclear. I mean that the `configure` file/script, is not in the GitHub repository! So I cant install it unless I download it from your site.

**Comment by sergiomb2** [comment]
ah , when you checkout the code,  you need run 

    ./bootstrap 

to create `configure` , also create `configure` if you run (a new way, I don't know if it official) :

    autoreconf -fiv 

Also 
https://github.com/twaugh/patchutils/releases/download/0.3.4/patchutils-0.3.4.tar.xz have `configure` file

**Comment by twaugh** [comment]
We could certainly use a README.md that briefly explains the purpose of the package and how to build and install it. Any volunteers?

**Comment by sergiomb2** [comment]
Hi, 
https://github.com/sergiomb2/patchutils/blob/master/README.md
what else ? any suggestion ?

**Comment by twaugh** [comment]
It's a good start, @sergiomb2. How about renaming the existing `README` and converting it to markdown? Could put the name of the project at the top as a heading, and have each tool name in bold or something.

Then after that, a sub-heading for 'installing', with what you have in there.

**Comment by sergiomb2** [comment]
I propose my last commit in my branch:
https://github.com/twaugh/patchutils/pull/16/commit/ef34c3a3d5d37055912caba370beca24c738c377

modify bootstrap to just be: https://github.com/sergiomb2/patchutils/blob/patchview/bootstrap and delete INSTALL file which is installed by autoreconf.
We still don't have Readme but before INSTALL file could give some confusion, since now we expect people run ./bootstrap , which generate this INSTALL file.

**Comment by sergiomb2** [comment]
Still valid https://github.com/sergiomb2/patchutils/commit/ef34c3a3d5d37055912caba370beca24c738c377

Delete INSTALL file can be a start ... 

Sorry for my terrible English.
